services:
  mysql:
    image: mysql:8.0
    container_name: biblioteca_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_biblioteca_data:/var/lib/mysql

volumes:
  mysql_biblioteca_data: